apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-operator
  namespace: keptn
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keptn-operator
  template:
    metadata:
      labels:
        name: keptn-operator
    spec:
      serviceAccountName: keptn-operator
      containers:
        - name: keptn-operator
          # Replace this with the built image name
          image: bacherfl/keptn-operator:v0.0.3
          command:
          - keptn-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keptn-operator"
