kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keptn-operator
  namespace: keptn
subjects:
- kind: ServiceAccount
  name: keptn-operator
roleRef:
  kind: Role
  name: keptn-operator
  apiGroup: rbac.authorization.k8s.io
