// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCore":       schema_pkg_apis_core_v1alpha1_KeptnCore(ref),
		"github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreSpec":   schema_pkg_apis_core_v1alpha1_KeptnCoreSpec(ref),
		"github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreStatus": schema_pkg_apis_core_v1alpha1_KeptnCoreStatus(ref),
	}
}

func schema_pkg_apis_core_v1alpha1_KeptnCore(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeptnCore is the Schema for the keptncores API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreSpec", "github.com/keptn/keptn-operator/pkg/apis/core/v1alpha1.KeptnCoreStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_core_v1alpha1_KeptnCoreSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeptnCoreSpec defines the desired state of KeptnCore",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_core_v1alpha1_KeptnCoreStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KeptnCoreStatus defines the observed state of KeptnCore",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
